import { useEffect, useState } from "react";
import toast from "react-hot-toast";

import DashboardLayout from "../layouts/DashboardLayout";
import HistoryCard from "../components/HistoryCard";
import api from "../api/api";

export default function History() {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const res = await api.get("/ai/history");
      setHistory(res.data);
    } catch (err) {
      toast.error("Failed to load history");
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>

      <div className="space-y-6">

        <div>
          <h1 className="text-4xl font-bold">
            Email History
          </h1>

          <p className="text-gray-500 mt-2">
            All emails generated by your account.
          </p>
        </div>

        {loading ? (

          <div className="bg-white rounded-xl shadow p-10 text-center">

            Loading...

          </div>

        ) : history.length === 0 ? (

          <div className="bg-white rounded-xl shadow p-10 text-center">

            No emails generated yet.

          </div>

        ) : (

          <div className="space-y-5">

            {history.map((item) => (
              <HistoryCard
                key={item._id}
                email={item}
              />
            ))}

          </div>

        )}

      </div>

    </DashboardLayout>
  );
}